### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by simplesoftwaregr** [VivaPayments/mobile-android-cardterminal-interapp-sample#1]
Hello, 
trying to connect to Android Card terminal (Α920) with socket programming, i think the documentation is wrong about the response i get.
My post is: 0063|002690|200|00|{0}|{1}|0000|||| 
In case of success i get: 0014|810|00|6454470106|002690|210|00|00|00|MASTERCARD|************8327|637225|409171|000001|0.01|1010|00|00|00|00|00|00|16031060
I case of error i get: 0014|810|00|9058770054|931616|210|00|CE|00|00|00|00|00|00|0000|0000|21032335

the thing is that those responses does not match with the documentation and i don;t know what to do with them. Can you please help?

**Comment by simplesoftwaregr** [comment]
??

**Comment by matthewrgourd** [comment]
Hi @simplesoftwaregr, apologies, I only just saw this. I'm going to find out and get back to you. Thank you.

**Comment by matthewrgourd** [comment]
Hi @simplesoftwaregr our development team has replied with the following:

>We've checked the API and it is aligned with our developer docs. Probably you're using an old Card Terminal app version in your PAX terminal. The latest is v1.15.0.

Hope this helps!
