### ISSUE TITLE
How to install on a phyiscal PAX A920 device ?

### ISSUE THREAD

**Issue by FilipBE** [VivaPayments/mobile-android-cardterminal-interapp-sample#2]
Hi,

I compiled the example and I can run it on both the emulator and on my Android mobile phone, but how do I get it onto the PAX A920 ? 
I can not seem to find it anywhere in the doc. Same for the settings password. 

Thx,

Filip.

**Comment by matthewrgourd** [comment]
Hi @FilipBE, apologies, I only just saw this. I'm going to find out and get back to you. Thank you.

**Comment by matthewrgourd** [comment]
During development for COTS Android mobile devices, installation of the sample code follows the standard procedure, the same as for any other Android app.
 
During development for the PAX Android terminal, it is more complicated. Currently we don't have a standard process. You would need to contact our business / product teams for them to perform an evaluation.
